config/routes.rb
Rails.application.routes.draw do
  resources :posts, except: [:show] do
    collection do
      get 'filter/:tag_name', to: 'posts#filter', as: 'filter'
    end
  end

  root 'posts#index'

end

app/models/post.rb
# self-explanatory
class Post < ActiveRecord::Base
  # validates :author, presence: true
  # validates :title, presence: true
  # validates :body, presence: true

  has_and_belongs_to_many :tags

  validate :author?
  validate :title?
  validate :body?

  validate :tags?

  def author?
    errors.add(:author, 'Author can\'t be blank') if author.blank?
  end

  def title?
    errors.add(:title, 'Title can\'t be blank') if title.blank?
  end

  def body?
    errors.add(:body, 'Body can\'t be blank') if body.blank?
  end

  def tags?
    errors.add(:tags_string,
               'Tags string must have at least one tag') if tags.blank?
  end

  def tags_string
    tags.map(&:name).join(', ')
  end

  def tags_string=(names)
    self.tags = names.split(/\s?,\s?|\s/).map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end
end

app/models/tag.rb
# self-explanatory
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  validates :name, presence: true, uniqueness: true

  def to_param
    name
  end
end

app/controllers/application_controller.rb
# self-explanatory
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
# self-explanatory
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @tags = sort_tags(Tag.all).reverse
    @posts = sort_posts(Post.all).reverse
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def filter
    @posts = sort_posts(Post.tagged_with(params[:tag_name])).reverse
    @tags = sort_tags(Tag.all).reverse

    render :index
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was created.' }
        format.json { render :index, status: :created }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to root_path, notice: 'Post was updated.' }
        format.json { render :index, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    @tags = Tag.all
    @tags.each do |tag|
      tag.destroy if tag.posts.empty?
    end
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust params from the Internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:author, :title, :body, :tags_string)
  end

  def sort_tags(tags)
    tags.sort_by do |tag|
      tag.posts.count
    end
  end

  def sort_posts(posts)
    posts.sort_by(&:updated_at)
  end
end

app/helpers/application_helper.rb
# self-explanatory
module ApplicationHelper
end

app/helpers/posts_helper.rb
# self-explanatory
module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "My Own Twitter"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  body
    .container
      = bootstrap_flash
      = yield

app/views/posts/_form.html.slim
= form_for @post, :html => { :class => "new post" } do |f|
  .form-group
    = f.label :author, class:  'control-label'
    = f.error_span :author
    = f.text_field :author, class:  'form-control'
  .form-group
    = f.label :title, class: 'control-label'
    = f.error_span :title
    = f.text_field :title, class:  'form-control'
  .form-group
    = f.label :body, class: 'control-label'
    = f.error_span :body
    = f.text_area :body, class: 'form-control'
  .form-group
    = f.label :tags_string, class: 'control-label'
    = f.error_span :tags_string
    = f.text_field :tags_string, class:  'form-control'
  = f.submit nil, class: 'btn btn-primary'
  = link_to t('.cancel', default: t("helpers.links.cancel")), posts_path, class:'btn btn-default'

app/views/posts/edit.html.slim
- model_class = Post
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/posts/index.html.slim
- model_class = Post
.page-header
  h1
    = link_to t('.title', :default => model_class.model_name.human.pluralize.titleize), root_path
h4.text-center
  b
    | Filter by tag
.row
  .col-xs-12.text-center
    - @tags.each do |tag|
      = link_to tag.name, filter_posts_path(tag), class: 'filter-by-tag'
hr.custom-hr
= link_to t('.new', :default => t("New Post")), new_post_path, :class => 'btn btn-lg btn-primary'
hr.custom-hr
table.table.table-striped
  tbody
    - @posts.each do |post|
      tr id="post-row-#{post.id}"
        td[width="150"]
          div.post-author
            strong = post.author
          hr
          div.post-tags
            = post.tags_string
        td
          div.post-title
            = post.title
          hr.style-three
          div.post-body
            = post.body
        td[width="100"]
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(post), :class => 'btn btn-default'
          hr.style-three
          = link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(post), :method => :delete, :class => 'btn btn-danger'

app/views/posts/new.html.slim
- model_class = Post
h1
  =t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/posts/show.html.slim
- model_class = Post
.page-header
  h1
    =t '.title', :default => model_class.model_name.human.titleize
dl.dl-horizontal
  dt
    strong
      = model_class.human_attribute_name(:author)
      | :
  dd
    = @post.author
  dt
    strong
      = model_class.human_attribute_name(:title)
      | :
  dd
    = @post.title
  dt
    strong
      = model_class.human_attribute_name(:body)
      | :
  dd
    = @post.body
= link_to t('.back', :default => t("helpers.links.back")), posts_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(@post), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(@post), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'